// Mirrors the design system's tokens/colors.css. Keep in sync with that file
// if the captain ever swaps the Warm/Playful palette (readme.md caveat #1).
export const THEME_NAMES = ['original', 'warm', 'playful'] as const;
export type ThemeName = (typeof THEME_NAMES)[number];
export const DEFAULT_THEME: ThemeName = 'warm';

export type ThemeVars = Record<string, string>;

export const THEMES: Record<ThemeName, ThemeVars> = {
  // Sunday Market: cream page, sage/apricot/butter pastels, soft brown ink.
  warm: {
    '--page': '#f7f1e8',
    '--surface': '#fffaf3',
    '--surface-2': '#f1e7da',
    '--surface-3': '#e8dccb',
    '--ink': '#3a2f28',
    '--ink-2': '#6b5a4c',
    '--ink-muted': '#9a8a7c',
    '--gridline': '#eee3d5',
    '--baseline': '#d7c7b3',
    '--border': 'rgba(58,47,40,0.10)',
    '--accent': '#a9562a',
    '--accent-soft': '#fbe0c8',
    '--accent-2': '#55733f',
    '--sage-soft': '#dfe8d5',
    '--butter': '#fff3c9',
    '--status-good': '#6f9152',
    '--status-bad': '#b3412e',
    '--cat-expenses': '#5f8fb0',
    '--cat-debt': '#cf7a55',
    '--cat-taiwan': '#5c9a7e',
    '--cat-emergency': '#d0a043',
    '--cat-savings': '#c0708d',
    '--cat-pinatubo': '#83a05a',
    '--cat-excess': '#a3785f',
  },
  original: {
    '--page': '#f9f9f7',
    '--surface': '#fcfcfb',
    '--surface-2': '#f2f1ec',
    '--surface-3': '#e9e7df',
    '--ink': '#0b0b0b',
    '--ink-2': '#52514e',
    '--ink-muted': '#898781',
    '--gridline': '#e1e0d9',
    '--baseline': '#c3c2b7',
    '--border': 'rgba(11,11,11,0.10)',
    '--accent': '#4a3aa7',
    '--accent-soft': 'rgba(74,58,167,0.10)',
    '--accent-2': '#4a3aa7',
    '--sage-soft': '#e9efe4',
    '--butter': '#fbf4dc',
    '--status-good': '#0ca30c',
    '--status-bad': '#c0392b',
    '--cat-expenses': '#2a78d6',
    '--cat-debt': '#eb6834',
    '--cat-taiwan': '#1baf7a',
    '--cat-emergency': '#eda100',
    '--cat-savings': '#e87ba4',
    '--cat-pinatubo': '#008300',
    '--cat-excess': '#4a3aa7',
  },
  playful: {
    '--page': '#f6f4fb',
    '--surface': '#ffffff',
    '--surface-2': '#efe9fb',
    '--surface-3': '#e3d9f7',
    '--ink': '#181022',
    '--ink-2': '#544a66',
    '--ink-muted': '#8c81a0',
    '--gridline': '#e6ddf5',
    '--baseline': '#cbb9ec',
    '--border': 'rgba(24,16,34,0.10)',
    '--accent': '#7c3aed',
    '--accent-soft': 'rgba(124,58,237,0.12)',
    '--accent-2': '#ec4899',
    '--sage-soft': '#e3f4ea',
    '--butter': '#fff4d6',
    '--status-good': '#16a34a',
    '--status-bad': '#e11d48',
    '--cat-expenses': '#2f6fed',
    '--cat-debt': '#f0592e',
    '--cat-taiwan': '#0d9488',
    '--cat-emergency': '#f5a300',
    '--cat-savings': '#ec4899',
    '--cat-pinatubo': '#22c55e',
    '--cat-excess': '#7c3aed',
  },
};

